/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppClinicsIndexRouteImport } from './routes/_app.clinics.index'
import { Route as AppClinicsIdRouteImport } from './routes/_app.clinics.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicsIndexRoute = AppClinicsIndexRouteImport.update({
  id: '/clinics/',
  path: '/clinics/',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicsIdRoute = AppClinicsIdRouteImport.update({
  id: '/clinics/$id',
  path: '/clinics/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof AppSettingsRoute
  '/clinics/$id': typeof AppClinicsIdRoute
  '/clinics/': typeof AppClinicsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/clinics/$id': typeof AppClinicsIdRoute
  '/clinics': typeof AppClinicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clinics/$id': typeof AppClinicsIdRoute
  '/_app/clinics/': typeof AppClinicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/settings' | '/clinics/$id' | '/clinics/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/settings' | '/' | '/clinics/$id' | '/clinics'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/settings'
    | '/_app/'
    | '/_app/clinics/$id'
    | '/_app/clinics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clinics/': {
      id: '/_app/clinics/'
      path: '/clinics'
      fullPath: '/clinics/'
      preLoaderRoute: typeof AppClinicsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clinics/$id': {
      id: '/_app/clinics/$id'
      path: '/clinics/$id'
      fullPath: '/clinics/$id'
      preLoaderRoute: typeof AppClinicsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClinicsIdRoute: typeof AppClinicsIdRoute
  AppClinicsIndexRoute: typeof AppClinicsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppClinicsIdRoute: AppClinicsIdRoute,
  AppClinicsIndexRoute: AppClinicsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
